name: e_commerce_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

# ================= Packages =================
dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  readmore: ^3.0.0
  smooth_page_indicator: ^1.1.0

# ================= Packages End =============
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # ================= Assets =================
  # *** Images/Icon/Fonts ****
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  # *** Fonts ****
  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/Euclid Circular A Bold Italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Euclid Circular A Bold.ttf
          weight: 700

        - asset: assets/fonts/Euclid Circular A SemiBold Italic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Euclid Circular A SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Euclid Circular A Medium Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Euclid Circular A Medium.ttf
          weight: 500

        - asset: assets/fonts/Euclid Circular A Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Euclid Circular A Regular.ttf
          weight: 400

        - asset: assets/fonts/Euclid Circular A Light Italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Euclid Circular A Light.ttf
          weight: 300
